config/routes.rb
Rails.application.routes.draw do
  get "about_me" => 'zhis#about_me'
  get "my_blogs" => 'zhis#index'
  
  get "tag/:tag", to: "blogs#tag", as: "tag"
  get "search", to: "zhis#search"

  resources :blogs
  resources :songs
  resources :image_descs

  root "zhis#every_snatch"
end

app/models/blog.rb
class Blog < ActiveRecord::Base

  belongs_to :category, class_name: "ModuleType"
  has_many :comments, class_name: "Message"

  validates :title, :content, presence: true
  default_scope {where("id != 1")}

  def tags
    return WordTag.where("id in (#{self.tag_ids})") if self.tag_ids.presence
    []
  end

  def content
    super.to_s.gsub(/class\=\"table/, 'class="am-table')
  end

  def keywords
    tags.collect{|wt| wt.name}.join(",") if tags
  end

  def post_time
    created_at.strftime("%F %T")
  end
  
end

app/models/image_desc.rb
class ImageDesc < ActiveRecord::Base
  scope :avilable, -> {where("photo_id > 24")}

  def picture
    Picture.where(bean_id: id, bean: "ImageDesc").last
  end

  def desc
    desc_zh_CN
  end

  def real_url
    WebHost + picture.file_path.to_s.split("public")[1] rescue nil 
  end
end

app/models/ip.rb
#encoding utf-8
class Ip < ActiveRecord::Base
  has_many :trackers
  default_value_for :num, 0

  def self.find_or_create(option = {})
    ip_address = Ip.where(option).first_or_create
    ip_address.num += 1
    ip_address.save
    ip_address
  end

  def china_ip?
    Province.all.collect(&:name).each {|pn| return true if self.location =~ /#{pn}/ }
    false
  end
end

app/models/module_type.rb
class ModuleType < ActiveRecord::Base
  scope :photos, -> {where(bean: "ImageDesc")}  
end

app/models/picture.rb
class Picture < ActiveRecord::Base

end

app/models/province.rb
class Province < ActiveRecord::Base
end

app/models/singer.rb
class Singer < ActiveRecord::Base
  has_many :songs

  def picture
    "/system/Singers/#{self.id}.jpg"
  end
  
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :singer
  scope :uncolsed, -> {where("type_id != 18")}
  
  def desc
    desc_zh_CN 
  end

  def pictures
    pics = Picture.where(bean: 'Song', bean_id: self.id)
  end
  
  def path
    "/system/Songs/#{self.id}.mp3"
  end

  def closed?
    type_id == 18
  end
  
  def type
    ModuleType.find_by_id(self.type_id).try(:name)
  end
  
  class << self
    def me
      where("type_id != 18").order("sing_time DESC")
    end

    def default
       where(is_default: true).last
    end
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  establish_connection "my"
end

app/models/tracker.rb
class Tracker < ActiveRecord::Base
  belongs_to :ip
  
  def ip_address
    ip.name
  end

  def ip_location
    ip.location
  end
end

app/models/word_tag.rb
class WordTag < ActiveRecord::Base
  def blogs
    Blog.where("tag_ids is not null").select{|b| b.tags.include?(self)}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :track_user

  private
    def udpate_show_times(obj)
      obj.transaction do
        obj.browse_times += 1
        obj.save
      end
    end

    def page_objs(objs, num = 10, pa = :page)
      return objs.page(params[pa]).per(num) if objs.is_a?(ActiveRecord::Relation)
      Kaminari.paginate_array(objs).page(params[pa]).per(num)
    end
  
    def track_user(f = "website")
      url = request.path + request.query_string 
      ip_address = Ip.find_or_create(name: request.remote_ip, location: get_ip_address)
      Tracker.create(user_agent: request.user_agent,web_url: url, data_from: f, ip_id: ip_address.id, host: request.host)
    end

    def get_ip_address
      IPParse.parse(request.ip)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def tag
    tg = WordTag.where(name: params[:tag]).first
    @blogs = page_objs(tg ? tg.blogs : [])
    render "zhis/index"
  end
  
  def show
    @blog = Blog.find_by_id(params[:id])
    return @error = "No This Blog" if !@blog
    udpate_show_times @blog
    @page_title = @blog.title
  end
  
  def comment
    @blog = Blog.find(params[:blog_id])
    return flash[:notice] = @notice = red_content(t(:comment_not_empty)) if params[:message].empty? || params[:message] =~ /href[=]*|\<script|http|www|\.c[omn]+/
    save_message({message: params[:message]}, @blog)
    @blog.save
  end
end

app/controllers/image_descs_controller.rb
class ImageDescsController < ApplicationController
    
  def index
    @image_descs = ImageDesc.avilable
    @image_desc = ImageDesc.find_by_id(params[:id]) || ImageDesc.last
    @page_title = "#{@image_desc.desc} - #{t(:szm)}"
    render "index"
  end
  
  def show
    index
    udpate_show_times @image_desc
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    
  def index
    @songs = Song.me
    @song = Song.find_by_id(params[:id]) || Song.last
    @page_title = "#{@song.name} - #{t(:szm)}"
    render "index"
  end
  
  def show
    index
    udpate_show_times @song
  end
end

app/controllers/zhis_controller.rb
class ZhisController < ApplicationController
  def index
    @blogs = page_objs(Blog.order("created_at DESC"))
    get_common
  end
  
  def about_me
    @blog = Blog.unscoped.first
  end

  def search
    get_common 
    @k = params[:k]
    if @k.to_s =~ /[\_\%\\\?\/\>\<\*\&\^\#]+/
      @blogs = page_objs Blog.where("id > 100000")
    else
      @blogs = page_objs(Blog.where("content like '%#{@k}%' or title like '%#{@k}%'"))
    end
    render :index
  end

  def every_snatch
    index
    render :index
  end

  private
    def get_common
      @late_blogs = Blog.order("created_at DESC").limit(5)
      @photos = ImageDesc.avilable.order("created_at DESC").limit(4)
      @state = State.last
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_menu(boo)
    boo ? "am-active" : ""
  end

  def short_blog(blog, num = 500, keep_span = true)
    (blog.content.gsub(/<[^>]*>/, "")[0, num] +
    "<a href='/blogs/#{blog.id}' target='_blank'><font color='#FF9900'><font size='2'>&lt;#{t(:reading_more)}&gt;</font></font></a>").html_safe
  end

  def into_datetime(time)
    time.strftime("%F %T")
  end
end

app/views/blogs/show.html.erb
<% if @blog %>
  <div class="am-u-sm-12 am-article text-center">
    <h1 class="am-article-title"><%= @blog.title %></h1>
    <p class="am-article-meta"><%= @blog.post_time %></p>
  </div>
  <hr class="am-article-divider"/>
  <div class="am-u-sm-12 am-article">
    <div class="am-u-md-12 ">
        <div class="am-u-sm-11 am-u-sm-centered">
          <div class="am-cf am-article">
             <%= raw @blog.content %>
          </div>
          <hr/>
        </div>
    </div>
    <div class="am-u-md-3 am-u-md-pull-9 my-sidebar">
      <div class="am-offcanvas" id="sidebar">
        <div class="am-offcanvas-bar">
          <ul class="am-nav">
            <li><a href="#"><%= t :my_blogs %></a></li>
            <li class="am-nav-header">目录</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <%= render "shared/error_tip", objs: [] %>
<% end %>

app/views/image_descs/index.html.slim
.admin-content
  ul.am-avg-sm-2.am-avg-md-4.am-avg-lg-6.am-margin.gallery-list
    - @image_descs.each do |image|
      li
        = image_tag image.real_url,class: "am-img-thumbnail am-img-bdrs"
        .gallery-title = image.desc
        .gallery-desc = image.pic_time

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title><%= @page_title || t(:website_title) %></title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
        content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="format-detection" content="telephone=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp"/>
  <link rel="alternate icon" type="image/png" href="/assets/i/favicon.png">
  <link rel="stylesheet" href="/assets/css/amazeui.min.css"/>
  <%= stylesheet_link_tag "application" %>
  <meta name="Description" content="<%= t :website_desc %>">
  <meta name="Keywords" content="<%= t :website_keywords %>">
  <style>
    @media only screen and (min-width: 1200px) {
      .blog-g-fixed {
        max-width: 1200px;
      }
    }

    @media only screen and (min-width: 641px) {
      .blog-sidebar {
        font-size: 1.4rem;
      }
    }

    .blog-main {
      padding: 20px 0;
    }

    .blog-title {
      margin: 10px 0 20px 0;
    }

    .blog-meta {
      font-size: 14px;
      margin: 10px 0 20px 0;
      color: #222;
    }

    .blog-meta a {
      color: #27ae60;
    }

    .blog-pagination a {
      font-size: 1.4rem;
    }

    .blog-team li {
      padding: 4px;
    }

    .blog-team img {
      margin-bottom: 0;
    }

    .blog-content img,
    .blog-team img {
      max-width: 100%;
      height: auto;
    }

    .blog-footer {
      padding: 10px 0;
      text-align: center;
    }
  </style>
</head>
<body>
<header class="am-topbar">
  <h1 class="am-topbar-brand">
      <a href="<%= OldWebHost %>" class="am-btn am-btn-primary am-btn-sm"><%= t(:old_version) %></a>
  </h1>

  <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only"
          data-am-collapse="{target: '#doc-topbar-collapse'}"><span class="am-sr-only">导航切换</span> <span
      class="am-icon-bars"></span></button>

  <div class="am-collapse am-topbar-collapse" id="doc-topbar-collapse">
    <ul class="am-nav am-nav-pills am-topbar-nav">
      <!-- <li class="<%= active_menu(request.path == "/") %>"> <%= link_to t(:every_snatch), root_path %></li> -->
      <li class="<%= active_menu(request.path == my_blogs_path) %>"> <%= link_to t(:my_blogs), my_blogs_path %></li>
      <li class="<%= active_menu(request.path == songs_path) %>"> <%= link_to t(:songs), songs_path %></li>
      <li><%= link_to t(:my_photos), OldWebHost + "/my_photos" %></li>
      <li class="<%= active_menu(request.path =~ /about_me/) %>"> <%= link_to t(:about_me), about_me_path %></li>
    </ul>

    <form class="am-topbar-form am-topbar-left am-form-inline am-topbar-right" role="search" action="/search">
      <div class="am-form-group">
        <input type="text" class="am-form-field am-input-sm" placeholder="<%= @k || "搜索文章" %>" name="k">
      </div>
      <button type="submit" class="am-btn am-btn-default am-btn-sm">搜索</button>
    </form>

  </div>
  <script src="/assets/js/jquery.min.js"></script>
</header>
<%= yield %>
<footer class="blog-footer">
  <p><%= t :website_footer %><br/>
    <small>© Copyright. by Zhimeng Sun.</small>
  </p>
</footer>

<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="assets/js/polyfill/rem.min.js"></script>
<script src="assets/js/polyfill/respond.min.js"></script>
<script src="assets/js/amazeui.legacy.js"></script>
<![endif]-->

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="/assets/js/amazeui.min.js"></script>
<!--<![endif]-->

</body>
</html>

app/views/shared/_error_tip.html.erb
<div class="am-alert am-alert-<%= objs.empty? ? "danger" : "success"%>" data-am-alert="">
  <button type="button" class="am-close">×</button>
  <p><%= objs.empty? ? "您到火星了吗？？" : "共检索到#{objs.size}条结果" %></p>
</div>

app/views/songs/_form.html.erb
<div class="new_table">
    <h3><%= action_name == "new" ? t(:create_song) : t(:edit_song)  %></h3>
    <%= form_for @song, :html => { :multipart => true}  do |f|  %>
    <%= render "/shared/error_messages", :target => @song %>
    <table class="form" width="80%">
          <tr>
            <td><%= t :song_name %></td>
            <td><%= text_field "song", "name", :size => 60, :class => "text min-length-3 bad-words"  %> </td>
          </tr>
          <tr>
             <td><%= t :sing_time %></td>
             <td><%= f.datetime_select :sing_time, :use_month_numbers => true, :order => [:year, :month, :day]  %></td>
          </tr>
          <tr>
              <td><%= t :type %></td>
              <td><%= select "song", "type_id", ModuleType.song_types.collect{|m| [m.name,m.id]}  %></td>
          </tr>
          <tr>
              <td><%= t :is_default %></td>
              <td><%= select "song", "is_default", [[0, false], [1, true]] %></td>
          </tr>
          <tr>
              <td><%= t :singer %></td>
              <td id="singer_name" colspan="2" >
                  <select id="song_singer_id" name="song[singer_id]" onchange="document.getElementById('singerPic').src='/images/singers/'+this.value+'.jpg'">
                    <% Singer.all.each do |s| %>
                        <option value="<%= s.id %>" <%= "selected='selected'" if @song.singer_id == s.id %>><%= s.name %></option>
                    <% end %>
                  </select>
                  <%=link_to_function t(:new_singer), "$('#singer_name').html('<input name=\"singer_name\" />');$('#singer_picture').html('<input name=\"singer_picture\" type=\"file\">');" %>
              </td>
          </tr>
          <tr>
              <td><%= t :picture %></td>
              <td id="singer_picture">
                  <img src="/system/Singers/<%=@song.singer_id || "1" %>.jpg" id="singerPic"/>
              </td>
          </tr>
          <tr>
              <td><%= t :select_song %></td>
              <td><%= file_field_tag :song_file %></td>
          </tr>
          <tr>
              <td><%= f.label t(:desc) + " English" %></td>
              <td><%= f.text_area :desc_en, :rows => 5, :cols => 70 %></td>
          </tr>
          <tr>
              <td><%= f.label t(:desc) + " 中文" %></td>
              <td><%= f.text_area :desc_zh_CN, :rows => 5, :cols => 70 %></td>
          </tr>
          <%= save_and_return f %>
        </table>
      <% end %>
    </div>
<div id="clr"></div>

app/views/songs/_player.html.erb
<%= javascript_include_tag "/assets/js/jquery.jplayer.min","/assets/js/jquery.jplayer.inspector" %>
<%= stylesheet_link_tag "application" %> 
<div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div class="control" id="jp_container_1">
  <div class="pause">
    <a href="javascript:;" class="jp-play" tabindex="1" ><img src="/images/Playv2.png"></a>
    <a href="javascript:;" class="jp-pause" tabindex="1" ><img src="/images/Pausev2.png"></a>
  </div>
  <div class="music">
    <div class="music_name"></div>
    <div class="bar jp-progress">
      <div class="bar_show jp-seek-bar">
        <div class="bar_h jp-play-bar"></div>
      </div>
    </div>
    <div class="music_time">
      <span class="jp-current-time"></span>/<span class="jp-duration"></span>
    </div>
  </div>
</div>

<script type="text/javascript">
  //<![CDATA[
  $(document).ready(function(){
    $("#jquery_jplayer_1").jPlayer({
      ready: function () {
        $(this).jPlayer("setMedia", {mp3: "<%= WebHost + @song.try(:path).to_s %>"}).jPlayer("play");
      },
      swfPath: "/",
      supplied: "mp3",
      wmode: "window"
    });
    $('.pause').hover(
      function(){
        $('.pause > .jp-play > img').attr('src',"/images/Play_sv2.png");
        $('.pause > .jp-pause > img').attr('src',"/images/Pause_sv2.png");
      },
      function(){
        $('.pause > .jp-play > img').attr('src',"/images/Playv2.png");
        $('.pause > .jp-pause > img').attr('src',"/images/Pausev2.png");
      }
    );
  });
  //]]>
</script>

app/views/songs/edit.html.erb
<%= render 'form' %>

app/views/songs/index.slim
.am-g.am-g-fixed
  .mod-avator.clearfix
    h2.am-article-title.text-center
      span = @song.try(:name) 
    #dewplayer_content = render "player" 
    h6.am-padding.text-center = @song.try(:desc) 
  .am-u-md-12
    .am-panel-group
      table.am-table.am-table-bordered
        - @songs.each do |song| 
          tr.song
            td = link_to song.name, song_path(song)
            // td = "(#{ song.type })"
            td = song.browse_times.to_s + "次"
            td = into_datetime song.sing_time

app/views/songs/new.html.erb
<%= render 'form' %>

app/views/zhis/about_me.html.erb
<div class="am-g am-g-fixed">
  <div class="am-u-md-12">
    <%= raw @blog.content %>
  </div>
</div>

app/views/zhis/index.html.erb
<div class="am-g am-g-fixed blog-g-fixed">
  <div class="am-u-md-<%= action_name == 'tag' ? 12 : 8 %>">
    <% if %w(search tag).include?(action_name) %>
      <%= render "shared/error_tip", objs: @blogs %>
    <% end %> 
    <% @blogs.each do |blog| %> 
      <article class="blog">
        <h3 class="am-article-title blog-title">
          <%= link_to blog.title, blog_path(blog) %></a>
        </h3>
        <p>
          <% blog.tags.each do |tag| %>
            <%= link_to tag.name, tag_path(tag: tag.name), 
                class: "am-badge am-badge-#{%w(success danger warning).sample}" %>
          <% end %>
        </p>
        <p class="blog"> <%= raw short_blog(blog) %></p>
        <p class="am-article-meta">
          <span class="am-icon-eye"></span>  <%= blog.browse_times %>
          <span class="am-icon-th ml10"></span>  <%= blog.post_time %>
        </p>
      </article>
      <hr class="am-article-divider blog-hr">
    <% end %> 
    <%= paginate @blogs %>
  </div>
  <% if action_name != 'tag' %>
    <div class="am-u-md-4 blog-sidebar">
      <div class="am-panel-group">
        <section class="am-panel am-panel-default">
          <div class="am-panel-hd"><%= t(:latest_state) %></div>
          <div class="am-panel-bd">
            <p><%= @state.description %></p>
            <i><%= @state.created_at %></i>
          </div>
        </section>
        <section class="am-panel am-panel-default">
          <div class="am-panel-hd"><%= t :latest_blogs %></div>
          <ul class="am-list blog-list">
            <% @late_blogs.each do |blog| %> 
              <li><%= link_to blog.title, blog_path(blog) %></li>
            <% end %> 
          </ul>
        </section>

        <section class="am-panel am-panel-default">
          <div class="am-panel-hd"><%= t :latest_pictures %></div>
          <div class="am-panel-bd">
            <ul class="am-avg-sm-4 blog-team">
              <% @photos.each do |photo| 
                 next if photo.real_url.nil? %> 
                <li><%= image_tag photo.real_url ,class: "am-thumbnail" %></li>
              <% end %> 
            </ul>
          </div>
        </section>
      </div>
    </div>
  <% end %>
</div>